name: FD_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  # google_fonts: 
  # google_maps_flutter: ^0.5.21+15
  location: ^2.3.5
  geolocator:
  geocoder: ^0.2.1
  # flutter_html: 1.1.1
  # webview_flutter: 
  # flutter_markdown: 
  # markdown: 
  # html2md: 
  # http: 
  # permission_handler: ^5.0.1+1
  # rxdart:
  map: 
  provider: ^3.1.0
  # geoflutterfire: 1.0.0 
  flutter_spinkit: "^4.0.0"
  image_picker: 0.6.0+17
  image_cropper: ^1.3.1
  firebase_storage:
  cached_network_image: ^2.5.1
  flutter_colorpicker:
  square_in_app_payments: ^1.2.3
  barcode_scan:
  latlng:
  qr_flutter:
  url_launcher:
  flutter_slidable:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.15.8
  outline_material_icons: ^0.1.0
  font_awesome_flutter: ^8.2.0
  shared_preferences: ^0.5.12+4
  flutter_icons:
  cupertino_icons:
dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^1.3.3
  page_transition: "^1.1.7+6"
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Font/GothamMedium.ttf
          weight: 200
        - asset: fonts/Gotham-Font/GothamBold.ttf
          weight: 500
        - asset: fonts/Gotham-Font/GothamLight.ttf
          weight: 700
        - asset: fonts/Gotham-Font/GothamBook.ttf
          weight: 400
    - family: Quarion
      fonts:
        - asset: fonts/Quarion/Quarion-ExtraLight.ttf
          weight: 200
        - asset: fonts/Quarion/Quarion-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Quarion/Quarion-Hairline.ttf
        - asset: fonts/Quarion/Quarion-HairlineItalic.ttf
          style: italic

        - asset: fonts/Quarion/Quarion-ExtraBold.ttf
          weight: 800
        - asset: fonts/Quarion/Quarion-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Quarion/Quarion-Bold.ttf
          weight: 700
        - asset: fonts/Quarion/Quarion-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Quarion/Quarion-Medium.ttf
          weight: 500
        - asset: fonts/Quarion/Quarion-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Quarion/Quarion-Heavy.ttf
          weight: 900
        - asset: fonts/Quarion/Quarion-HeavyItalic.ttf
          weight: 900
          style: italic

        - asset: fonts/Quarion/Quarion-SemiBold.ttf
          weight: 600
        - asset: fonts/Quarion/Quarion-SemiBoldItalic.ttf
          weight: 600
          style: italic
        
        - asset: fonts/Quarion/Quarion-Thin.ttf
          weight: 100
        - asset: fonts/Quarion/Quarion-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: fonts/Quarion/Quarion-Light.ttf
          weight: 300
        - asset: fonts/Quarion/Quarion-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Quarion/Quarion-Book.ttf
        - asset: fonts/Quarion/Quarion-BookItalic.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
