class Language {
  static Map<String, String> mapLang;
  static String lang;
  static Map<String, String> mapFR = {
    'yep': 'oui',
    'home': 'Accueil',
    'hello': 'Bonjour',
    'explore': 'Explorer',
    'profile': 'Profil',
    'title': 'titre',
    'change': 'Modifier',
    'orders': 'mes Commandes',
    'order': 'Commander',
    'signin': 'Se connecter',
    'register': "S'inscrire",
    'welcomeback': 'Nous Saluons Le Retour',
    'password': 'mot de passe',
    'login': 'connexion',
    'cancel': 'Annuler',
    'createaccount': 'Créer un Compte',
    'editprofile': 'Modifier le profil',
    'edit': 'Modifier',
    'changeemail': "Changer l'e-mail",
    'settings': 'Les paramètres',
    'changepassword': 'Changer le mot de passe',
    'account': 'Compte',
    'signout': 'Se déconnecter',
    'passwordvalidator': 'entrez un mot de passe de plus de 6 caractères.',
    'passwordmatch': "La confirmation ne correspond pas au mot de passe.",
    'emailvalidator': 'Veuillez saisir une adresse e-mail valide',
    'nointernet': 'Vérifiez votre connection internet',
    'sendemail': 'Envoyer un e-mail',
    'forgetpassword': 'Mot de passe oublié?',
    'ERROR_INVALID_EMAIL': 'Votre adresse e-mail semble incorrecte.',
    'ERROR_WRONG_PASSWORD': 'Votre mot de passe est incorrect.',
    'ERROR_USER_NOT_FOUND': "L'utilisateur avec cet e-mail n'existe pas.",
    'ERROR_USER_DISABLED': "L'utilisateur avec cet e-mail a été désactivé.",
    'ERROR_TOO_MANY_REQUESTS': "Trop de demandes. Réessayez plus tard.",
    'ERROR_OPERATION_NOT_ALLOWED':
        "La connexion avec e-mail et mot de passe n'est pas activée.",
    'UNDEFINED_ERROR': "Une erreur non définie s'est produite.",
    'accounttype': 'Type de compte',
    'customer': 'Client',
    'enterprise': 'Entreprise',
    'oldpassword': 'Ancien mot de passe',
    'changenewpassword': 'Changer le nouveau mot de passe',
    'error': 'Erreur',
    'validate': 'Valider',
    'newemail': 'Nouvel e-mail',
    'enterpassword': 'tapez votre mot de passe',
    'changenewemail': 'changer le nouvel e-mail',
    'aboutus': 'À propos de nous',
    'changelang': 'Changer la langue',
    'fr': 'français',
    'en': 'Anglais',
    'rateus': 'Evaluez nous',
    'submit': 'Soumettre',
    'favorite': 'Favoris',
    'bestweek': 'Le meilleur de la semaine',
    'closetoyou': 'Près de vous',
    'call': 'Appel',
    'mail': 'Courrier',
    'pictures': 'Photos',
    'typehere': 'écrivez ici',
    'personalinfo': 'Information personnelle',
    'firstname': 'Prénom',
    'lastname': 'Nom',
    'phone': 'Tél',
    'city': 'Ville',
    'sexe': 'Sexe',
    'address': 'Adresse',
    'deliverymen': 'Livreurs',
    'time': "Heure",
    'placeorder': 'Passer une commande',
    'finish': 'Terminer',
    'cod': 'Paiement à la livraison',
    'card': 'Carte de crédit',
    'next': 'Suivant',
    'required': 'Champs obligatoires',
    'carcolor': 'Couleur de la voiture',
    'redirectClToLv':
        "chargement..., vous serez bientôt redirigé vers l'espace livreur",
    'pickcolor': 'Choisissez une couleur',
    'matricule': 'Matricule',
    'choose': 'Choisir',
    'confirm': 'Confirmer',
    'modepay': 'Mode de paiement',
    'pay': 'Payer',
    'viewall': 'Voir tout',
    'LOCATION_PERMISSION_DENIED':
        'Access to the location service has been declined',
    'dragchoose': 'Faites glisser pour choisir',
    'detail': 'Détail',
    'orderdetail': 'Détail du commande',
    'number': 'Numéro',
    'ftype': 'Type de carburant',
    'show': 'Afficher',
    'areyousure': 'êtes-vous sûr?',
    'usedlang': 'vous utilisez déjà cette langue',
    'accesslocation': "nous avons besoin d'accéder à votre emplacement",
    'locateme': 'Localiser moi',
    'delete': 'Effacer',
    'stnolv': "cette station n'a pas de livreurs",
    'deliveredASAP': 'sera livré dès que possible',
    'open': 'Ouvrir',
    'upload': 'télécharger',
    'imagenotfound': "impossible de charger l'image",
    'invalidnumber': 'numéro invalide',
    'invalidcin': 'cin invalide',
    'fueltodoor': "Obtenez le carburant livré à votre porte.",
    'work24/7': 'Travaillant 24/7',
    'start': 'commencer',
    'onlyletters': 'seules les lettres sont autorisées'
  };
  static Map<String, String> mapEN = {
    'home': 'Home',
    'yep': 'yes',
    'hello': 'Hello',
    'title': 'title',
    'change': 'Change',
    'explore': 'Explore',
    'profile': 'Profile',
    'orders': 'My Orders',
    'order': 'Order',
    'signin': 'Sign in',
    'register': "Register",
    'welcomeback': 'Welcome Back',
    'password': 'password',
    'login': 'Log in',
    'createaccount': 'Create an account',
    'editprofile': 'Edit profile',
    'edit': 'Edit',
    'upload': 'upload',
    'changeemail': "Change email",
    'settings': 'Settings',
    'changepassword': 'change password',
    'account': 'Account',
    'detail': 'Detail',
    'orderdetail': 'Order detail',
    'signout': 'Sign out',
    'passwordvalidator': 'enter a password 6+ chars long.',
    'passwordmatch': 'confirmation do not match the password.',
    'emailvalidator': 'Please supply a valid email',
    'nointernet': 'Check your internet connection',
    'sendemail': 'Send Email',
    'cancel': 'Cancel',
    'forgetpassword': 'Forgot your password?',
    'ERROR_INVALID_EMAIL': 'Your email address appears to be malformed.',
    'ERROR_WRONG_PASSWORD': 'Your password is wrong.',
    'ERROR_USER_NOT_FOUND': 'User with this email doesn\'t exist.',
    'ERROR_USER_DISABLED': 'User with this email has been disabled.',
    'ERROR_TOO_MANY_REQUESTS': 'Too many requests. Try again later.',
    'ERROR_OPERATION_NOT_ALLOWED':
        'Signing in with Email and Password is not enabled.',
    'UNDEFINED_ERROR': 'An undefined Error happened.',
    'accounttype': 'Account type',
    'customer': 'Customer',
    'enterprise': 'Enterprise',
    'oldpassword': 'Old password',
    'changenewpassword': 'Change the new password',
    'error': 'Error',
    'validate': 'Validate',
    'newemail': 'New email',
    'enterpassword': 'enter your password',
    'changenewemail': 'change new email',
    'aboutus': 'About us',
    'changelang': 'Change the language',
    'fr': 'French',
    'en': 'English',
    'rateus': 'Rate us',
    'submit': 'Submit',
    'favorite': 'Favorites',
    'bestweek': 'The best of the week',
    'closetoyou': 'Close to you',
    'call': 'Appel',
    'mail': 'Mail',
    'pictures': 'Pictures',
    'typehere': 'type here',
    'personalinfo': 'Personal information',
    'firstname': 'First name',
    'lastname': 'Last name',
    'phone': 'Phone',
    'city': 'City',
    'sexe': 'Gender',
    'address': 'Address',
    'deliverymen': 'Deliverymen',
    'placeorder': 'Place an order',
    'time': "Time",
    'finish': 'Finish',
    'cod': 'Cash on delivery',
    'card': 'Credit Card',
    'next': 'Next',
    'confirm': 'Confirm',
    'required': 'Required',
    'carcolor': 'Car Color',
    'pickcolor': 'Pick a color',
    'matricule': 'Reg. N°',
    'choose': 'Choose',
    'modepay': 'Payment method',
    'pay': 'Pay',
    'viewall': 'View all',
    'LOCATION_PERMISSION_DENIED':
        "L'accès au service de localisation a été refusé",
    'dragchoose': 'Drag to choose',
    'number': 'Number',
    'ftype': 'Fuel type',
    'show': 'Show',
    'areyousure': 'are you sure?',
    'redirectClToLv':
        "chargement..., vous serez bientôt redirigé vers l'espace livreur",
    'usedlang': 'you are already using this language',
    'accesslocation': 'we need access to your location',
    'locateme': 'Locate me',
    'delete': 'Delete',
    'stnolv': 'this station does not have delivery men',
    'deliveredASAP': 'will be delivered ASAP',
    'open': 'Open',
    'imagenotfound': "unable to load image",
    'invalidnumber': 'invalid number',
    'invalidcin': 'invalid cin',
    'fueltodoor': "Get the fuel delivered to your door.",
    'work24/7': 'Working 24/7',
    'start': 'Start',
    'onlyletters': 'only letters allowed'
  };
  static toggleLang(String lang) {
    if (lang == 'EN') {
      Language.mapLang = mapEN;
    } else {
      Language.mapLang = mapFR;
    }
  }
}

List<String> cities = [
  'Casablanca',
  'Rabat',
  'Fes',
  'Marrakesh',
  'Tangier',
  'Sale',
  'Meknes',
  'Agadir',
  'Khenifra',
  'Oujda',
  'Kenitra',
  'Tetouan',
  'Asfi',
  'Safi',
  'Temara',
  'Inezgane',
  'El Aaiun',
  'Mohammedia',
  'Khouribga',
  'Beni Mellal',
  'Nador',
  'El Jadida',
  'Taza',
  'Ait Melloul',
  'Larache',
  'Taourirt',
  'Guelmim',
  'Settat',
  'Khemisset',
  'Ksar el-Kebir',
  'Khemis Sahel',
  'Al Hoceima',
  'Imzouren',
  'Errachidia',
  'Oued Zem',
  'Tarudant',
  'Fkih Ben Saleh',
  'Berkane',
  'Sidi Qasim',
  'Sidi Slimane',
  'Sidi Kacem',
  'Tiznit',
  'Ben Guerir',
  'Essaouira',
  'Tiflet',
  'El Kelaa des Sraghna',
  'Oulad Teima',
  'Youssoufia',
  'Wazzan',
  'Sefrou',
  'Tan-Tan',
  'Azrou',
  "M'diq",
  'Ouazzane',
  'Guercif',
  'Ouarzazate',
  'Dakhla',
  'Fnideq',
  'Lahraouyine',
  'Suq as-Sabt Awlad an-Nama',
  'Driouch',
  'Boujad',
  'Ben Slimane',
  'Sidi Bennour',
  'Midelt',
  'Souk El Arbaa',
  'Skhirat',
  'Smara',
  'Ain Harrouda',
  'Cape Bojador',
  'Kasba Tadla',
  'Azemmour',
  'Sidi Bouzid',
  'Lqliaa',
  'Azimur',
  'Tinghir',
  'Mrirt',
  'Al Aaroui',
  'Chefchaouen',
  'Zagora',
  'El Aioun Sidi Mellouk',
  'Beni Ansar',
  'Taounate',
  'Sidi Yahya El Gharb',
  'Asilah',
  'Azilal',
  'Jerada',
  'Martil',
  'Amalou Ighriben',
  'Bouznika',
  'Tawnat',
  'El Hajeb',
  'Biougra',
  'Tahla',
  'Ihddaden',
  'Ain El Aouda',
  'Bouarfa',
  'Aguelmous',
  'Arfoud',
  'Demnate',
  'Sidi Slimane Echcharraa',
  'Zaouiat Cheikh',
  'Ain Taoujdate',
  'Echemmaia',
  'Aourir',
  'Oulad Ayad',
  'Ben Ahmed',
  'Tabounte',
  'Missour',
  'Jorf El Melha',
  'Rissani',
  'Segangan',
  'Er-Rich',
  'Ait Ourir',
  'Sidi Ifni',
  'Sidi Taibi',
  'Ahfir',
  'El Ksiba',
  'Saidia',
  'Goulmima',
  'Imintanoute',
  'Drarga',
  'Bouderbala',
  'Mehdya',
  'Bouhdila',
  'Chichaoua',
  'Bni Bouayach',
  'Oulad Berhil',
  'Jamaat Shaim',
  'Bir Jdid',
  'Tata',
  'Boujniba',
  'Oulad Hriz Sahel',
  'Mediouna',
  "Kalaat M'Gouna",
  'Imouzzer Kandar',
  "Ain Bni Mathar",
  'Bouskoura',
  'Agourai',
  'Midar',
  'Ain Jemaa',
  'Lalla Mimouna',
  'Nouaceur',
  'Moulay Idriss Zerhoun',
  'Figuig',
  'Boumia',
  'Rommani',
  'Jorf',
  'Ifrane',
  'Bouizakarne',
  'Oulad M Barek',
  'Afourar',
  'Ait Ishaq',
  'Tit Mellil',
  'Assa',
  'Bhalil',
  'Targuist',
  'El Menzel',
  'Boumalne Dades',
  'Amizmiz',
  'Farkhana',
  'Boulanouare',
  'Ben Taieb',
  'Deroua',
  'El Marsa',
  'Agdz',
  'Tamanar',
  'Ait Iaaza',
  'Boudnib',
  'Dar Ould Zidouh',
  'Foum Zguid',
  'Tissa',
  'Jaadar',
  'Oulmes',
  'Bouknadel',
  'El Guerdane',
  'Selouane',
  "Maaziz",
  "Oulad M'Rah",
  'Aklim',
  'Ouaouizert',
  'Bni Drar',
  "N'Zalat Bni Amar",
  'El Kbab',
  'Oued Laou',
  'Oued Amlil',
  'Bni Tadjite',
  'Zag',
  'Sidi Ahmed',
  'Oulad Yaich',
  'Tinejdad',
  'Tighassaline',
  'Tounfit',
  'Akka',
  'Talsint',
  'Fam El Hisn',
  'Taghjijt',
  'Boulemane',
  'Zirara',
  'Tahannaout',
  'Bradia',
  'Moulay Abdallah',
  'El Ouatia',
  'Tameslouht',
  'Aghbala',
  'Tendrara',
  'Taznakht',
  'Dar Gueddari',
  'Itzer',
  'Taliouine',
  'Oualidia',
  'Aoulouz',
  'Moulay Bousselham',
  'Tarfaya',
  'Ghafsai',
  'Foum Jamaa',
  'Ain Leuh',
  'Moulay Bouazza',
  'Had Kourt',
  'Loulad',
  'Zaida',
  'Tafraout',
  'El Hanchane',
  'Sidi Jaber',
  'Irherm',
  'Debdou',
  'Ras Kebdana',
  'Ain Cheggag',
  'Bzou',
  'Lakhsas',
  'Oulad Zbair',
  'Bni Chiker',
  'Talmest',
  'Aknoul',
  'Bab Taza',
  'Tiztoutine',
  'Imouzzer Marmoucha',
  'Ajdir',
  'Gourrama',
  'Zoumi',
  'Thar Essouk',
  'Zrarda',
  'Ras El Ain',
  'Sebt Jahjouh',
  'Tafersit',
  'Touissit',
  'Lalla Takerkoust',
  'Bouanane',
  'Soualem',
  'Alnif',
  'Sidi Allal Tazi',
  'Dar El Kebdani',
  'El Jebha',
  'Ain Erreggada',
  'Skoura',
  'Smimou',
  'Timahdite',
  'Ait Daoud',
  'Souk El Had',
  'Had Bouhssoussen',
  'Oulad Said',
  'Arbaoua',
  'Ain Dorij',
  'Madagh',
  'Tighza',
  'Matmata',
  'Kerouna',
  'Bni Hadifa',
  'Kerrouchen',
  'Guisser',
  'Sidi Boubker',
  'Tamassint',
  'Assahrij',
  'Sidi Bou Othmane',
  'Sidi Rahhal',
  'Issaguen',
  'Bouguedra',
  'Brikcha',
  'Ighoud',
  'Aoufous',
  'Tafetachte',
  'Ahrara',
  'Ounagha',
];
